### ISSUE TITLE
React & Redux group project: set up your Kanban board and assigning tasks

### ISSUE THREAD

**Issue by NatiDeme** [NatiDeme/space-traveler#63]
# Changes to find in this issue list:
- Assigned tasks to each member.
- Kanban board was copied properly.
- Implemented git flow.

# Link to Github project
https://github.com/NatiDeme/space-traveler/projects/2

# Project Group Members:
Natnael  @NatiDeme 
Hanningtone @HanningtoneM

**Comment by zhadier** [comment]
Hi @NatiDeme , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue without mentioning the Project Kanban board link and the information about the number of people in your group as was clearly required in the Project description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @NatiDeme and @HanningtoneM,

Good job so far!
✔️ Kanban columns are well set up
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your board appears to be missing this task from the copied project (see image). Ensure you add it.

  ![rocket-booking](https://user-images.githubusercontent.com/36542986/179483997-7e3e33c5-9084-402d-bbae-6216252582ec.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
